name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go latest
        uses: actions/setup-go@v4

      - run: go version

      - name: Vet
        run: go vet ./...

      - name: Install
        run: go install -v ./...

      - name: Test
        run: go test -cover -coverprofile coverage.out -covermode=atomic -race ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
